### ISSUE TITLE
Issue - Unable to create dynamic child route

### ISSUE THREAD

**Issue by Thomas-Ballard** [sitecorelabs/xmcloud-foundation-head-dev#104]
Hello - thank you for building out this starter kit.

I am running into the following issue where I need to implement a wildcard page under a separate catch-all route.
My structure is as follows, with the main path file not being edited past logging. 

- pages/
  - api/...
  - [[...path]].tsx
  - events/
    - [...path]].tsx
    
It appears, due to the remapping of props in the middleware.ts file, the first level path file always gets the requests regardless of the URL provided.

If I disable the events/ in the matcher file for the middleware, I get a 404 for these URLs but the path file in the events folder is called which is what I expect.

Could you please provide guidance on the implementation of this structure, to allow for a match-all dynamic route + wildcard page in XM Cloud, or what would need to be adapted in provided middleware layer for this to work as expected.

Many thanks
Tom

**Comment by ambrauer** [comment]
Hi @Thomas-Ballard! As this is a generic JSS question, can I ask you to please move this over to the [Sitecore JSS repository](https://github.com/Sitecore/jss)? I would suggest starting with a [Discussion (Help category)](https://github.com/Sitecore/jss/discussions/categories/help) as it seems like a configuration problem at first glance. 

The larger JSS community may be able to help, and the JSS team monitors this as well.

Thanks in advance 🙏

**Comment by Thomas-Ballard** [comment]
Hi @ambrauer, ok will do - thanks
