### ISSUE TITLE
Upgrade to JSS 21.6.4

### ISSUE THREAD

**Issue by sebastiantecsi** [sitecorelabs/xmcloud-foundation-head-dev#164]
Hello,

Since this release https://github.com/Sitecore/jss/releases/tag/v21.6.4 is the latest, is there a plan to have the foundation head for xmcloud be updated to the latest version of jss? 

And what is the general plan to get things updated to latest jss release for foundation head for xmcloud?
Or do I have myself to update to latest jss after I use the foundation head for xmcloud everytime I create a new project and I see that we are not on the latest ?

Thank you,
Sebastian

**Comment by ambrauer** [comment]
Hi @sebastiantecsi - Thanks for bringing this to our attention. The `xmcloud-foundation-head*` repos should be updated for every release of JSS (_including patch versions_), but looks like this was skipped with the 21.6.x releases as the team was focused on an upcoming 21.7 release. Going forward you can expect this to occur. 

The next update here will come with the JSS 21.7.0 release, landing this week or next. If you wanted the 21.6.4 updates before then, you would need to perform that update manually.
